apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-deployment
  labels:
    app: jwt
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jwt
  template:
    metadata:
      labels:
        app: jwt
    spec:
      containers:
      - name: jwt
        image: 851725430072.dkr.ecr.sa-east-1.amazonaws.com/jwt-master:latest
        ports:
        - containerPort: 80