name: Deploy to AWS EKS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA4MTWKVU4IHQXR5TD
          aws-secret-access-key: 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
          aws-region: sa-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 851725430072.dkr.ecr.sa-east-1.amazonaws.com
          ECR_REPOSITORY: jwt-master
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Set up Kubeconfig
        run: |
          aws eks --region sa-east-1 update-kubeconfig --name auth-k8s

      - name: Deploy to EKS
        run: |
          kubectl apply -f .github/workflows/deployment.yml
          kubectl apply -f .github/workflows/service.yml